Change Reactive Messaging dependency from org.eclipse to io.smallrye due to NoSuchMethodError: org/eclipse/microprofile/reactive/messaging/Message.getMetadata
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>